# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod
mod_id=tag_stacker
mod_version=1.0.0

# Dependencies
minecraft_version=1.21.1
minecraft_range=[1.21.1]

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Neo
loader_range=[1,)
neo_version=21.1.144
neo_range=[21.1.144,)

# Optional Dependencies - Mantle has nice utilities
# mantle_version=1.11.94
