@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.tagstacker.jei;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;