@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.tagstacker;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;